id: I16661B68
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T20:36:25+00:00'
last_modified: '2022-06-10T05:24:26.544897+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG0619
  title: བོད་ཀྱི་རྩོམ་ལུས་རྣམ་བཤད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    9FFD:
      image_group_id: I4CZ354566
      title: Volume 1 of bod kyi rtsom lus rnam bshad
      total_pages: 232
      order: 1
      base_file: 9FFD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
